pub const CAMERA_DEFAULT_OFFSET_X: f32 = 0.0;
pub const CAMERA_DEFAULT_OFFSET_Y: f32 = 0.0;
pub const CAMERA_DEFAULT_ZOOM: f32 = 1.0;

pub const ERR_FRAMEBUFFER_OVERFLOW: &str = "Frame buffer dimensions overflow.";
pub const ERR_FRAMEBUFFER_SIZE: &str = "Frame buffer is smaller than expected for RGB24.";
pub const ERR_FRAMEBUFFER_INVALID_DIMENSIONS: &str = "Invalid framebuffer dimensions.";
pub const FRAMEBUFFER_ERR_WIDTH_U32_OVERFLOW: &str = "frame width does not fit in u32";
pub const FRAMEBUFFER_ERR_HEIGHT_U32_OVERFLOW: &str = "frame height does not fit in u32";
pub const FRAMEBUFFER_ERR_ENGINE_INIT_FAILED_PREFIX: &str = "doom_engine_init failed with status";
pub const FRAMEBUFFER_ERR_ENGINE_FILL_FAILED_PREFIX: &str =
    "doom_engine_fill_frame failed with status";
pub const FRAMEBUFFER_ERR_ENGINE_SET_WORLD_FAILED_PREFIX: &str =
    "doom_engine_set_world failed with status";
pub const FRAMEBUFFER_ERR_ENGINE_SET_SPAWN_FAILED_PREFIX: &str =
    "doom_engine_set_player_spawn failed with status";

pub const RGB_CHANNELS: usize = 3;
pub const RENDER_CELL_SOLID: &str = " ";
pub const RENDER_CELL_DENSITY_HEAVY: &str = "▓";
pub const RENDER_CELL_UPPER_HALF: &str = "▀";
pub const FRAMEBUFFER_STATUS_RESERVED_ROWS: usize = 1;

pub const FRAMEBUFFER_SAMPLE_GRID_BASE: usize = 3;
pub const FRAMEBUFFER_SAMPLE_GRID_MIN: usize = 1;
pub const FRAMEBUFFER_SAMPLE_GRID_MAX: usize = 3;
pub const FRAMEBUFFER_SAMPLE_GRID_EDGE_DETECTION: usize = 3;
pub const FRAMEBUFFER_SAMPLE_GRID_PROBE_MIN: usize = 2;
pub const FRAMEBUFFER_EDGE_DETECTION_THRESHOLD: u8 = 22;
pub const FRAMEBUFFER_SAMPLE_POSITION_CENTER_OFFSET: f32 = 0.5;

pub const FRAMEBUFFER_UNSHARP_STRENGTH: f32 = 0.34;
pub const FRAMEBUFFER_ADAPTIVE_LOW_CONTRAST_DELTA: u8 = 12;
pub const FRAMEBUFFER_ADAPTIVE_HIGH_CONTRAST_DELTA: u8 = 36;
pub const FRAMEBUFFER_GAMMA: f32 = 0.78;
pub const FRAMEBUFFER_CONTRAST: f32 = 1.16;
pub const FRAMEBUFFER_MIDPOINT: f32 = 0.46;
pub const FRAMEBUFFER_SHADOW_LIFT: f32 = 0.04;
pub const FRAMEBUFFER_SOFT_CLIP: f32 = 0.88;
pub const FRAMEBUFFER_SOFT_CLIP_STRENGTH: f32 = 0.55;
pub const FRAMEBUFFER_SATURATION_BOOST: f32 = 1.1;
pub const FRAMEBUFFER_UI_SHARPEN_TOP_END_RATIO: f32 = 0.4;
pub const FRAMEBUFFER_UI_SHARPEN_BOTTOM_START_RATIO: f32 = 0.62;
pub const FRAMEBUFFER_UI_SHARPEN_BONUS: f32 = 0.12;
pub const FRAMEBUFFER_UI_SHARPEN_BOTTOM_EXTRA_BONUS: f32 = 0.04;
pub const FRAMEBUFFER_FLAT_CELL_THRESHOLD: u8 = 14;
pub const FRAMEBUFFER_SOFT_BLEND_CELL_THRESHOLD: u8 = 48;
pub const FRAMEBUFFER_HALF_BLOCK_LUMA_THRESHOLD: u8 = 24;
pub const FRAMEBUFFER_DENSITY_LUMA_MAX: u8 = 10;
pub const FRAMEBUFFER_HEAVY_DENSITY_CHROMA_THRESHOLD: u8 = 80;
pub const FRAMEBUFFER_GLYPH_HYSTERESIS_LUMA: u8 = 8;
pub const FRAMEBUFFER_GLYPH_HYSTERESIS_CHROMA: u8 = 18;

pub const FRAMEBUFFER_VIEWPORT_MIN_SCALE_NUMERATOR: f32 = 1.0;
pub const FRAMEBUFFER_VIEWPORT_MIN_CELL_WIDTH: f32 = 1.0;
pub const FRAMEBUFFER_VIEWPORT_MIN_PIXEL_HEIGHT: f32 = 2.0;
pub const FRAMEBUFFER_VIEWPORT_TOP_OFFSET: usize = 0;
pub const FRAMEBUFFER_SIGNATURE_SAMPLE_SPLITS: usize = 2;
pub const FRAMEBUFFER_SIGNATURE_ROTATE_STEP_BITS: u32 = 11;

pub const FRAMEBUFFER_UNIT_INTERVAL_MIN: f32 = 0.0;
pub const FRAMEBUFFER_UNIT_INTERVAL_MAX: f32 = 1.0;
pub const FRAMEBUFFER_LUMA_RED_WEIGHT: u16 = 54;
pub const FRAMEBUFFER_LUMA_GREEN_WEIGHT: u16 = 183;
pub const FRAMEBUFFER_LUMA_BLUE_WEIGHT: u16 = 19;
pub const FRAMEBUFFER_LUMA_WEIGHT_DIVISOR: u16 = 256;
